services:
  # Your BMS app (prebuilt ARM64 image pushed to Docker Hub)
  bms:
    image: lumac1976/bms:arm64
    platform: linux/arm64
    container_name: bms-app
    restart: unless-stopped
    environment:
      # Point your app to InfluxDB (adjust if your app expects different vars)
      INFLUX_HOST: http://influxdb3-core:8181
      INFLUX_DB: bms
      INFLUX_ORG: default
      INFLUX_TOKEN: "apiv3_n7_oUpwKZ7m2k_Y2qTK3UY3S3Py7CG8n8ZPuNz2zyAfL88Hsuu7Mok8KBG8MxJcjAM9NjPA6X3HKUE7ES5HZTA"
    depends_on:
      - influxdb3

  influxdb3:
    image: influxdb:3-core
    container_name: influxdb3-core
    user: "${UID:-1000}:${GID:-1000}"
    # restart: on-failure:10
    ports:
      - "8181:8181"
    volumes:
      - ../config/influxdb3/core/data:/var/lib/influxdb3/data
      - ../config/influxdb3/core/plugins:/var/lib/influxdb3/plugins
    command:
          - influxdb3
          - serve
          - --node-id=node0
          - --object-store=file
          - --data-dir=/var/lib/influxdb3/data
          - --plugin-dir=/var/lib/influxdb3/plugins
          - --http-bind=0.0.0.0:8181
    environment:
      LOG_FILTER: debug